# Generated by Django 3.1.1 on 2020-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_comment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='hello', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='computer', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
