# Generated by Django 3.1.1 on 2020-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_appcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcomment',
            name='hasResponse',
            field=models.IntegerField(default=0),
        ),
    ]
