# Generated by Django 3.1.1 on 2020-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_appcomment_hasresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anonymous', max_length=10),
        ),
    ]
