# Generated by Django 3.1.1 on 2020-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html',
            field=models.TextField(default='<h1>Example</h1>'),
        ),
    ]
