# Generated by Django 3.1.1 on 2020-10-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_article_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
