# Generated by Django 3.1.1 on 2020-10-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_appcomment'),
        ('Managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Managers.manager')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.appcomment')),
            ],
        ),
    ]
